# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Catapult < Formula
  desc "A console application for file management and synchronization with GitHub using device flow authentication"
  homepage "https://github.com/itcaat/catapult"
  version "0.0.3"
  license "MIT"

  on_macos do
    url "https://github.com/itcaat/catapult/releases/download/v0.0.3/catapult_0.0.3_darwin_all.tar.gz"
    sha256 "c4bf3faa41444c55b0802852e39b7efa1f20931e5626d5a85a1111a5d9d2b802"

    def install
      bin.install "catapult"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/itcaat/catapult/releases/download/v0.0.3/catapult_0.0.3_linux_amd64.tar.gz"
      sha256 "4af1e87d416ff3b03cbb9af92d43cc62b5e16b05e25558b8a0525cb1b29928f8"
      def install
        bin.install "catapult"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/itcaat/catapult/releases/download/v0.0.3/catapult_0.0.3_linux_arm64.tar.gz"
      sha256 "b80c88176df892a94897c8059c1dc3d15c4c39cf7d57bf2c86c9cf7ad0867e90"
      def install
        bin.install "catapult"
      end
    end
  end

  test do
    system "#{bin}/catapult", "version"
  end
end
