# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Catapult < Formula
  desc "A console application for file management and synchronization with GitHub using device flow authentication"
  homepage "https://github.com/itcaat/catapult"
  version "0.0.5"
  license "MIT"

  on_macos do
    url "https://github.com/itcaat/catapult/releases/download/v0.0.5/catapult_0.0.5_darwin_all.tar.gz"
    sha256 "f2a5dff56304c7f0c1e1efbd8b88d2f687122b671379e349d4b46355725493db"

    def install
      bin.install "catapult"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/itcaat/catapult/releases/download/v0.0.5/catapult_0.0.5_linux_amd64.tar.gz"
      sha256 "a6433074f51ee76e167514a9617c22634c231cc522ba2313e8cc9707ec1ec51b"
      def install
        bin.install "catapult"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/itcaat/catapult/releases/download/v0.0.5/catapult_0.0.5_linux_arm64.tar.gz"
      sha256 "1e29cad5ade08873170faa06b808b0ad50f116ce22ccd1b5c1c6f8bfdfeb2f55"
      def install
        bin.install "catapult"
      end
    end
  end

  test do
    system "#{bin}/catapult", "version"
  end
end
