# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CliStash < Formula
  desc "A terminal UI application for saving and recalling shell commands"
  homepage "https://github.com/itcaat/cli-stash"
  version "0.1.3"
  license "MIT"

  on_macos do
    url "https://github.com/itcaat/cli-stash/releases/download/v0.1.3/cli-stash_0.1.3_darwin_all.tar.gz"
    sha256 "5b214fc5f3eb2018404f36490cf14830058cddf690e85451409b52fb6429c465"

    def install
      bin.install "cli-stash"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itcaat/cli-stash/releases/download/v0.1.3/cli-stash_0.1.3_linux_amd64.tar.gz"
      sha256 "3e8486e849bce33b44ebccbb7c6848e11bded47015ba0b93b675429f4ff6f8d7"
      def install
        bin.install "cli-stash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itcaat/cli-stash/releases/download/v0.1.3/cli-stash_0.1.3_linux_arm64.tar.gz"
      sha256 "1b80a5612c5de9addfc017ecd9c9b5554c0e7200b48da0edbf34576b23d38042"
      def install
        bin.install "cli-stash"
      end
    end
  end

  test do
    system "#{bin}/cli-stash", "help"
  end
end
