# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CliStash < Formula
  desc "A terminal UI application for saving and recalling shell commands"
  homepage "https://github.com/itcaat/cli-stash"
  version "0.2.8"
  license "MIT"

  on_macos do
    url "https://github.com/itcaat/cli-stash/releases/download/v0.2.8/cli-stash_0.2.8_darwin_all.tar.gz"
    sha256 "623a6e57099c2d1daf527f89ad37bf7ea30025eb3502a7cd9339371b5a8722d1"

    def install
      bin.install "cli-stash"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itcaat/cli-stash/releases/download/v0.2.8/cli-stash_0.2.8_linux_amd64.tar.gz"
      sha256 "dce79afd310cf87e1a62c24774b28740c51eadb143065320bbcc316f4e59b5a1"
      def install
        bin.install "cli-stash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itcaat/cli-stash/releases/download/v0.2.8/cli-stash_0.2.8_linux_arm64.tar.gz"
      sha256 "b12fe13dd26727bece809dddf75cc747bf4721cb23cf4b75abe4b8fd11b54fde"
      def install
        bin.install "cli-stash"
      end
    end
  end

  test do
    system "#{bin}/cli-stash", "help"
  end
end
