# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kvdiff < Formula
  desc "Compare HashiCorp Vault KV secret trees"
  homepage "https://github.com/itcaat/kvdiff"
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/itcaat/kvdiff/releases/download/v0.1.0/kvdiff_0.1.0_darwin_all.tar.gz"
    sha256 "61fe82e8311989c891324b1d10bd70c7a35e539cb296382e702ff34f5d85c094"

    define_method(:install) do
      bin.install "kvdiff"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itcaat/kvdiff/releases/download/v0.1.0/kvdiff_0.1.0_linux_amd64.tar.gz"
      sha256 "eecaf51bf4ac649b2484402b062eaa2a06759b6045152fef47ec8cd10e6fa64f"
      define_method(:install) do
        bin.install "kvdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itcaat/kvdiff/releases/download/v0.1.0/kvdiff_0.1.0_linux_arm64.tar.gz"
      sha256 "74af442506e4234cba26b86ecd4ce25914ea334d94b4108d24d841021e8eda26"
      define_method(:install) do
        bin.install "kvdiff"
      end
    end
  end

  test do
    system "#{bin}/kvdiff", "--version"
  end
end
